version: "3"
services:
  richao-services-bot:
    image: richardleite/richao-services-bot
    container_name: richao-services-bot
    environment:
      - PUID=998
      - PGID=1000
      - TOKEN=Your_Token
      - CLIENT_ID=Your_Client_ID
      - GUILD_ID=Your_Guild_Id
      - MESSAGE_CREATE_CHANNEL_ID=0000
      - WELCOME_CHANNEL_ID=0000
      - WELCOME_CHANNEL_NAME=Your_Welcome_Channel_Name
      - MEMBERS_ROLE_ID=0000
      - MEMBERS_ROLE_NAME=Your_Members_Name
      - EXTERNAL_HOSTNAME=yoursite.com
      - INVITE_CODE=Your_Jfa_Go_Invite_Code
    ports:
      - 3000:3000
    restart: unless-stopped